import os
from qdrant_client import QdrantClient
from qdrant_client.http import models

# Qdrant host configuration (defaults to local docker container or cloud URL)
QDRANT_HOST = os.getenv("QDRANT_HOST", "localhost")
QDRANT_PORT = int(os.getenv("QDRANT_PORT", "6333"))
QDRANT_API_KEY = os.getenv("QDRANT_API_KEY", "")

def get_qdrant_client():
    """Initializes and returns Qdrant Client connection."""
    try:
        if QDRANT_API_KEY:
            client = QdrantClient(url=QDRANT_HOST, api_key=QDRANT_API_KEY)
        else:
            client = QdrantClient(host=QDRANT_HOST, port=QDRANT_PORT)
        return client
    except Exception as e:
        print(f"Warning: Failed to connect to Qdrant vector database: {str(e)}")
        return None

def initialize_collection(collection_name="pangnn_nodes", vector_size=32):
    """Creates a new vector space indexing schema in Qdrant."""
    client = get_qdrant_client()
    if client is None:
        return False
        
    try:
        # Check if collection already exists
        collections = client.get_collections().collections
        exists = any(c.name == collection_name for c in collections)
        
        if not exists:
            client.create_collection(
                collection_name=collection_name,
                vectors_config=models.VectorParams(
                    size=vector_size, # Size of embeddings generated by PanGNN hidden layers
                    distance=models.Distance.COSINE
                )
            )
            print(f"Qdrant collection '{collection_name}' initialized.")
        return True
    except Exception as e:
        print(f"Failed to initialize Qdrant collection: {str(e)}")
        return False

def upsert_node_embeddings(node_ids, embeddings, metadata, collection_name="pangnn_nodes"):
    """Inserts node vector embeddings into the vector database index."""
    client = get_qdrant_client()
    if client is None:
        return False
        
    try:
        points = []
        for idx, (node_id, vector, meta) in enumerate(zip(node_ids, embeddings, metadata)):
            points.append(
                models.PointStruct(
                    id=node_id,
                    vector=vector.tolist() if hasattr(vector, 'tolist') else vector,
                    payload=meta
                )
            )
            
        client.upsert(
            collection_name=collection_name,
            points=points
        )
        print(f"Successfully indexed {len(points)} node vectors in Qdrant.")
        return True
    except Exception as e:
        print(f"Failed to upsert node vectors: {str(e)}")
        return False
